### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fire** [Maumagnaguagno/HyperTensioN#1]
Hi,

I was investigating porting HyperTensioN to c++ / GDScript in the Godot Engine for games.

What license is this? Godot Engine is MIT licensed. As MIT license HyperTensioN would benefit many.

**Comment by Maumagnaguagno** [comment]
> I was investigating porting HyperTensioN to c++ / GDScript in the Godot Engine for games.

HyperTensioN generates its own code for improved performance, not that simple to port.
This is also not the right time to port it, as I am still updating things.

> What license is this?
As MIT license HyperTensioN would benefit many.

This project uses [No license](https://choosealicense.com/no-permission/), as every other project/repository without a license, which means the copyright belongs to the author(s).
I will not choose the MIT license in this project, as that would remove the need for others to give their improvements back, without any benefit for the project itself.

Perhaps in the future I change my mind, not today.
