### ISSUE TITLE
Pullup extension sometimes generates invalid plans

### ISSUE THREAD

**Issue by philher** [Maumagnaguagno/HyperTensioN#9]
Hi, 

While playing with different planners in my work, I noticed that the `pullup` extension sometimes leads to invalid plans.

Implementing something similar to the approach presented in [Compiling HTN Plan Verification Problems into HTN Planning Problems (Höller et al.)](https://bercher.net/publications/2022/Hoeller2022VerificationViaCompilation.pdf), I was able to generate some couples of domains and instance, for which no solution plan should exist, but HyperTensioN finds one if the `pullup` extension is enabled (the behaviour is correct if it is not activated).

I tried to simplify such a domain, which you can find attached, and it appears that branch removal allows pulling up the predicates too high in the hierarchy.
In this domain, the goal is to be able to reproduce a sequence of 3 observations, `obsact_0`, `obsact_1`, `obsact_2`, 
We use the `obsidx_X` predicate to keep track of where we are in the sequence, and we have an `impossible` predicate that is used to block some decompositions.
The primitive plan should therefore be exactly the sequence `obsact_0 -> obsact_1 -> obsact_2`, but when using HyperTensioN (both on the latest master (d644be59adbafe54bd45780deda98658d37be8c8) and tag [v2.2](https://github.com/Maumagnaguagno/HyperTensioN/tree/v2.2)), the sequence is `obsact_0 -> obsact_1 -> obsact_2 -> obsact_0`.

I have also converted the domain and instance to dot using your tools, and annotated it to show what appears to be the issue (`dom_annotated.pdf` shows the base domain, `dom_pullup_annotated.pdf` the domain using the pullup predicate).

I admit that the structure of this domain is quite a bit different from usual HTN domains, but I hope this information will help you improve your planner.

Let me know if you require more details.

Attached files:
+ Domain and instance: [dom_inst.zip](https://github.com/Maumagnaguagno/HyperTensioN/files/15077659/dom_inst.zip)
+ Dot base: [dom_annotated.pdf](https://github.com/Maumagnaguagno/HyperTensioN/files/15077664/dom_annotated.pdf)
+ Dot pullup: [dom_pullup_annotated.pdf](https://github.com/Maumagnaguagno/HyperTensioN/files/15077665/dom_pullup_annotated.pdf)

**Comment by Maumagnaguagno** [comment]
Thanks for the very well written report and files.
I confirm the incorrect behavior with the provided planning instance.
I was able to obtain a smaller reproducible example from your input.
The reproducible example is in JSHOP style, which I find more compact and easier to modify.
EDIT: I found a minimal reproducible example with one operator and two methods.

<details>
<summary>Domain</summary>

```Lisp
(defdomain test (

  (:operator (!act)
    ()
    ((pre))
    ()
  )

  (:method (t_repeat)
    ()
    (
      (t_op)
      (t_op)
    )
  )

  (:method (t_op)
    ((pre))
    ((!act))
  )
))
```
</details>

<details>
<summary>Problem</summary>

```Lisp
(defproblem prob test
  ((pre))
  ((t_repeat))
)
```
</details>

**Comment by Maumagnaguagno** [comment]
I found the source of the problem: clearing preconditions too soon for operators that appear as the first subtask and only once.
The problem is that such operator could be reached again through another subtask.
~~A fast solution is to comment the ``op[#].clear`` lines.~~
Tomorrow I will investigate more.
Please leave the issue open until this is resolved.

**Comment by Maumagnaguagno** [comment]
It works!
Took me some time to retest everything.
Once tests are added a new version will be released.

Reopen this issue if you find other instances with the same behavior.
Thanks again for the feedback.
